/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 23:45:39 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Parse_ESTest extends Parse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Parse parse0 = new Parse();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      parse0.setEa(encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseVoluntarios("~aPe[3r,$m*d");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEncomenda(",J91,Q:g&ne]");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEncomenda(",M63o*DxS");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEmpresaTransportes("!,K.{");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Parse parse0 = new Parse();
      parse0.parse();
      Parse parse1 = new Parse(parse0);
      assertFalse(parse1.equals((Object)parse0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BDVoluntarios bDVoluntarios0 = new BDVoluntarios();
      BDUtilizador bDUtilizador0 = new BDUtilizador();
      BDLojas bDLojas0 = new BDLojas();
      BDTransportes bDTransportes0 = new BDTransportes();
      BDProdutos bDProdutos0 = new BDProdutos();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      BDGeral bDGeral0 = new BDGeral(bDVoluntarios0, bDUtilizador0, bDLojas0, bDTransportes0, bDProdutos0, encomendasAceites0);
      Utilizador utilizador0 = new Utilizador();
      ArrayList<Encomenda> arrayList0 = utilizador0.getEncomendas();
      Parse parse0 = new Parse(bDGeral0, arrayList0, encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Parse parse0 = new Parse();
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      EncomendasAceites encomendasAceites1 = parse0.parseEncomendasAceites("#=`w~hU", encomendasAceites0);
      assertSame(encomendasAceites1, encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Parse parse0 = new Parse();
      List<String> list0 = parse0.lerFicheiro("Z");
      assertFalse(list0.contains("Z"));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.setEncomendas((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseVoluntarios((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseUtilizador("?,x_V-T(8$r{,1e");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseUtilizador((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseLojas((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseLinhaEncomenda((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEmpresaTransportes((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.addEncomendasCliente((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.addEncomendas((List<Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Parse parse0 = new Parse();
      ArrayList<Locale.LanguageRange> arrayList0 = new ArrayList<Locale.LanguageRange>();
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>(0);
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) arrayList0, (Collection<String>) linkedHashSet0, locale_FilteringMode0);
      EncomendasAceites encomendasAceites0 = new EncomendasAceites(list0);
      parse0.addEncomendasAceites(encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.lerFicheiro((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.getBaseGeral();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("BDGeral", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Encomenda encomenda0 = new Encomenda();
      encomenda0.setEncomendaMedica(false);
      List<Encomenda> list0 = List.of(encomenda0, encomenda0, encomenda0, encomenda0, encomenda0, encomenda0, encomenda0, encomenda0, encomenda0);
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.addEncomendasVoluntariosETransportes(list0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Parse parse0 = new Parse();
      Encomenda encomenda0 = new Encomenda();
      List<Encomenda> list0 = List.of(encomenda0, encomenda0, encomenda0);
      parse0.addEncomendasVoluntariosETransportes(list0);
      assertEquals(3, list0.size());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Parse parse0 = new Parse();
      Encomenda encomenda0 = new Encomenda();
      List<Encomenda> list0 = List.of(encomenda0, encomenda0, encomenda0);
      parse0.addEncomendasCliente(list0);
      assertEquals(3, list0.size());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Parse parse0 = new Parse();
      Encomenda encomenda0 = new Encomenda();
      List<Encomenda> list0 = List.of(encomenda0, encomenda0, encomenda0);
      parse0.addEncomendas(list0);
      assertEquals(3, list0.size());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Parse parse0 = new Parse();
      Encomenda encomenda0 = new Encomenda();
      List<Encomenda> list0 = List.of(encomenda0, encomenda0, encomenda0);
      parse0.setEncomendas(list0);
      List<Encomenda> list1 = parse0.getEncomendas();
      assertTrue(list1.contains(encomenda0));
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseUtilizador(">9qK:Lt9IYXx.]?");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Parse parse0 = new Parse();
      Parse parse1 = null;
      try {
        parse1 = new Parse(parse0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("BDGeral", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseLinhaEncomenda("vQ3]S,g");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      EncomendasAceites encomendasAceites0 = new EncomendasAceites();
      Parse parse0 = null;
      try {
        parse0 = new Parse((BDGeral) null, (List<Encomenda>) null, encomendasAceites0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Parse parse0 = new Parse();
      List<Encomenda> list0 = parse0.getEncomendas();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.setEa((EncomendasAceites) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseEncomendasAceites((String) null, (EncomendasAceites) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Parse", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Parse parse0 = new Parse();
      EncomendasAceites encomendasAceites0 = parse0.getEa();
      assertNotNull(encomendasAceites0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Parse parse0 = new Parse();
      parse0.parse();
      BDGeral bDGeral0 = parse0.getBaseGeral();
      assertNotNull(bDGeral0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Parse parse0 = new Parse();
      // Undeclared exception!
      try { 
        parse0.parseLojas(",!&5'");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("Parse", e);
      }
  }
}
