/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 23:39:13 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TrazAqui_ESTest extends TrazAqui_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaNIF("3*7");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O NIF que inseriu \u00E9 inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaValoresFLOAT((-3916.2756F));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Inseriu um valor inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaValoresDOUBLE(0.0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Inseriu um valor inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaValoresINT((-748));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Inseriu um valor inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.codigoLogIn("\"5", 1693);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // O c\u00F3digo que inseriu nao est\u00E1 associado a nenhuma conta existente.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.pwVerificaC((String) null, "EncomendasAceites", 3387);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // A palavra passe que inseriu est\u00E1 incorreta.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      HashMap<String, Utilizadores> hashMap0 = new HashMap<String, Utilizadores>();
      trazAqui0.setInformacaoUtilizadores(hashMap0);
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Map<String, PlataformaEntrega> map0 = trazAqui0.getInformacaoPlataformaEntrega();
      trazAqui0.setInformacaoPlataformaEntrega(map0);
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      HashMap<String, Encomenda> hashMap0 = new HashMap<String, Encomenda>();
      trazAqui0.setInformacaoEncomenda(hashMap0);
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<EncomendasAceites> list0 = trazAqui0.getEncomendasRealizadas();
      trazAqui0.setEncomendasRealizadas(list0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      // Undeclared exception!
      try { 
        trazAqui0.tempoTransporteUtilizador("", encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      // Undeclared exception!
      try { 
        trazAqui0.tempoTransporteLoja("<;", encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseVoluntario("^8{{{4/,/Mh]8s|G");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseTransportadora("ox?,!sL");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      String[] stringArray0 = new String[6];
      stringArray0[3] = "0";
      // Undeclared exception!
      try { 
        trazAqui0.parseLinhaEncomenda(stringArray0, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseEncomenda("5,#`X3B+/cCz9bpQ&");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      trazAqui0.gravaFicheiro("0");
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Encomenda encomenda0 = new Encomenda();
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.encomendaAceite(encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Ponto ponto0 = new Ponto();
      Transportadoras transportadoras0 = new Transportadoras();
      Map<String, Encomenda> map0 = transportadoras0.getEncomendasGuardadas();
      Lojas lojas0 = new Lojas("P`O", "P`O", "P`O", ponto0, 55, map0);
      int int0 = trazAqui0.getTamanhoFila(lojas0);
      assertEquals(55, int0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Ponto ponto0 = new Ponto(133.0F, 133.0F);
      Utilizadores utilizadores0 = new Utilizadores();
      Map<String, Encomenda> map0 = utilizadores0.getEncomendasGuardadas();
      Lojas lojas0 = new Lojas("A localizacao da Plataforma de Entrega que est\u00E1 a tentar criar j\u00E1 est\u00E1 associada a uma Plataforma de Entrega existente.\n", "gcv.h(5do>&*", "gcv.h(5do>&*", ponto0, (-1002), map0);
      int int0 = trazAqui0.getTamanhoFila(lojas0);
      assertEquals((-1002), int0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.verificaNIF((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.totalDinheiroTempo("", (LocalDateTime) null, (LocalDateTime) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.totalDinheiro("Email: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.setInformacaoLojas((Map<String, Lojas>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      // Undeclared exception!
      try { 
        trazAqui0.podeTransportarV("v4.h0yw'J#8tFI4N/", encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      // Undeclared exception!
      try { 
        trazAqui0.podeTransportarT("9V>rw4`5f?8`i}", encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseVoluntario((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseUtilizador((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseTransportadora((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseTotal("-rC^Q");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseLoja("YwTI&,R\"c'ErPOm1,&)");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseLoja((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      String[] stringArray0 = new String[3];
      stringArray0[2] = "<am8`A%,)h4kBMW";
      // Undeclared exception!
      try { 
        trazAqui0.parseLinhaEncomenda(stringArray0, 0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        trazAqui0.parseLinhaEncomenda(stringArray0, 3);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 3 out of bounds for length 0
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseEncomenda((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.lerFicheiroTexto("_");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.leFicheiro((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.iniciarEntregaT("Aceite:");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      FileSystemHandling.shouldAllThrowIOExceptions();
      try { 
        trazAqui0.gravaFicheiro("Email: ");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.gravaFicheiro("");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.gravaCSV((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.gravaCSV("");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      // Undeclared exception!
      try { 
        trazAqui0.finalizarEntregaT(":d$UW9~R3nb@|9dc09", encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.finalizarEncomenda((Encomenda) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.addUtilizador((Utilizadores) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.addPlataforma((PlataformaEntrega) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.addLoja((Lojas) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.addEncomendaAceite((Encomenda) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.addEncomenda((Encomenda) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Map<String, Lojas> map0 = trazAqui0.getInformacaoLojas();
      Map<String, Utilizadores> map1 = trazAqui0.getInformacaoUtilizadores();
      LinkedList<EncomendasAceites> linkedList0 = new LinkedList<EncomendasAceites>();
      TrazAqui trazAqui1 = null;
      try {
        trazAqui1 = new TrazAqui((Map<String, PlataformaEntrega>) null, map0, map1, (Map<String, Encomenda>) null, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      TrazAqui trazAqui0 = null;
      try {
        trazAqui0 = new TrazAqui((TrazAqui) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<PlataformaEntrega> list0 = trazAqui0.ordenadoTop10T();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<PlataformaEntrega> list0 = trazAqui0.ordenadoCusto(false);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<PlataformaEntrega> list0 = trazAqui0.ordenadoClassificacoes(false);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      trazAqui0.addEncomenda(encomenda0);
      Map<String, Encomenda> map0 = trazAqui0.getInformacaoEncomenda();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.setInformacaoEncomenda((Map<String, Encomenda>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Map<String, Lojas> map0 = trazAqui0.getInformacaoLojas();
      trazAqui0.setInformacaoLojas(map0);
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.setInformacaoUtilizadores((Map<String, Utilizadores>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.setInformacaoPlataformaEntrega((Map<String, PlataformaEntrega>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.setEncomendasRealizadas((List<EncomendasAceites>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Ponto ponto0 = new Ponto();
      HashMap<String, Encomenda> hashMap0 = new HashMap<String, Encomenda>();
      Lojas lojas0 = new Lojas("TrazAqui", "TrazAqui", "0", ponto0, (-939), hashMap0);
      trazAqui0.addLoja(lojas0);
      trazAqui0.gravaCSV("S3X4j5iY");
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<PlataformaEntrega> list0 = trazAqui0.ordenadoTop10V();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<Utilizadores> list0 = trazAqui0.ordenadoTop10U();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<PlataformaEntrega> list0 = trazAqui0.ordenadoCusto(true);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<PlataformaEntrega> list0 = trazAqui0.ordenadoClassificacoes(true);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaNIF("~o;F7imlg");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O NIF que inseriu \u00E9 inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaNIF(")%]@A?DpQO4h");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // O NIF que inseriu \u00E9 inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaValoresFLOAT(0.0F);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Inseriu um valor inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      boolean boolean0 = trazAqui0.verificaValoresFLOAT(2538.1753F);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaValoresDOUBLE((-855.56101986972));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Inseriu um valor inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      boolean boolean0 = trazAqui0.verificaValoresDOUBLE(1.0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaValoresINT(0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Inseriu um valor inv\u00E1lido.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      boolean boolean0 = trazAqui0.verificaValoresINT(1209);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaT("bQ\"W9qg6lsHZ[zH.");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // A transportadora que inseriu n\u00E3o existe no nosso sistema.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaLoja("c");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // A loja que introduziu n\u00E3o existe no nosso sistema.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.verificaEncomenda((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // A encomenda que introduziu n\u00E3o existe no nosso sistema.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Encomenda encomenda0 = new Encomenda();
      TrazAqui trazAqui0 = new TrazAqui();
      trazAqui0.addEncomenda(encomenda0);
      boolean boolean0 = trazAqui0.verificaEncomenda("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Ponto ponto0 = new Ponto(0.0F, 0.0F);
      boolean boolean0 = trazAqui0.peVerifica("(0.0, 0.0)", ponto0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Ponto ponto0 = new Ponto();
      boolean boolean0 = trazAqui0.lojaVerifica("", ponto0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      boolean boolean0 = trazAqui0.codigoSignUp("dH'8>i1Y~28==]N");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      boolean boolean0 = trazAqui0.emailSignUp("uY ");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.codigoLogIn("xV?", 3);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // O c\u00F3digo que inseriu nao est\u00E1 associado a nenhuma conta existente.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.codigoLogIn((String) null, 2);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // O c\u00F3digo que inseriu nao est\u00E1 associado a nenhuma conta existente.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.codigoLogIn("", 1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // O c\u00F3digo que inseriu nao est\u00E1 associado a nenhuma conta existente.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.codigoLogIn("&<Urc=2X%U}^q", 4);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // O c\u00F3digo que inseriu nao est\u00E1 associado a nenhuma conta existente.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.emailLogIn("bQ\"W9qg6lsHZ[zH.");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // O email que inseriu nao est\u00E1 associado a nenhuma conta existente.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.pwVerificaE("", "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // A palavra passe que inseriu est\u00E1 incorreta.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.pwVerificaC("V{Z+v.*%m", "V{Z+v.*%m", 4);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.pwVerificaC("Ewai{: ", "Ewai{: ", (-1584));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // A palavra passe que inseriu est\u00E1 incorreta.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.pwVerificaC("", "", 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.pwVerificaC("Ewai{: ", "Ewai{: ", 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.pwVerificaC("Email: ", "Email: ", 2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      double double0 = trazAqui0.condicoesAtmosfericas();
      assertEquals(1.5, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Encomenda encomenda0 = new Encomenda();
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.escolhaVoluntario(encomenda0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Nenhum volunt\u00E1rio se encontra disponivel.
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      List<Transportadoras> list0 = trazAqui0.listPodeTransportarT(encomenda0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      int int0 = trazAqui0.tempoMedioAtendimento("");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Encomenda encomenda0 = new Encomenda();
      TrazAqui trazAqui0 = new TrazAqui();
      Transportadoras transportadoras0 = trazAqui0.recomendarBarata(encomenda0, false);
      assertNull(transportadoras0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      Transportadoras transportadoras0 = trazAqui0.recomendarClassificada(encomenda0, false);
      assertNull(transportadoras0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Utilizadores utilizadores0 = trazAqui0.getUtilizador("");
      assertNull(utilizadores0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      TrazAqui trazAqui1 = new TrazAqui(trazAqui0);
      boolean boolean0 = trazAqui1.equals(trazAqui0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      boolean boolean0 = trazAqui0.equals("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      boolean boolean0 = trazAqui0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      boolean boolean0 = trazAqui0.equals(trazAqui0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      HashMap<String, PlataformaEntrega> hashMap0 = new HashMap<String, PlataformaEntrega>();
      HashMap<String, Lojas> hashMap1 = new HashMap<String, Lojas>();
      HashMap<String, Utilizadores> hashMap2 = new HashMap<String, Utilizadores>();
      TrazAqui trazAqui0 = new TrazAqui();
      Map<String, Encomenda> map0 = trazAqui0.getInformacaoEncomenda();
      Lojas lojas0 = new Lojas();
      hashMap1.put(" NY'[0+I^QP=mT+<^;(", lojas0);
      TrazAqui trazAqui1 = new TrazAqui(hashMap0, hashMap1, hashMap2, map0, (List<EncomendasAceites>) null);
      // Undeclared exception!
      try { 
        trazAqui1.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.getTamanhoFila((Lojas) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      // Undeclared exception!
      try { 
        trazAqui0.finalizarEntregaV("", encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      String string0 = trazAqui0.toString();
      assertEquals("-- TrazAqui --\nPlataformas de Entrega:\n{}\nLojas:\n{}\nUtilizadores:\n{}\nEncomendas:\n{}\nEncomendas Realizadas: \n[]\n", string0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = trazAqui0.getEncomenda("");
      assertNull(encomenda0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Lojas lojas0 = trazAqui0.getLoja("~o;F7imlg");
      assertNull(lojas0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseLoja("3*7");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      TrazAqui trazAqui1 = trazAqui0.clone();
      assertNotSame(trazAqui1, trazAqui0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.classificarPlataformaEntrega("U: ", (-147));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Voluntarios voluntarios0 = new Voluntarios();
      trazAqui0.addPlataforma(voluntarios0);
      assertEquals("", voluntarios0.getCodigo());
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      try { 
        trazAqui0.leFicheiro("Sh-qFdW$");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.distanciaLoja("(0.0, 0.0)", "(0.0, 0.0)");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      List<PlataformaEntrega> list0 = trazAqui0.getPlataformaTipo("");
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.gravaFicheiro((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.parseUtilizador("#Y){,}iG8+^^g$FA; ");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 2 out of bounds for length 2
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      // Undeclared exception!
      try { 
        trazAqui0.custoTransporte("", encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Ponto ponto0 = new Ponto((-527.0F), (-527.0F));
      Map<String, Encomenda> map0 = trazAqui0.getInformacaoEncomenda();
      Utilizadores utilizadores0 = new Utilizadores("cMelhorCusto", "cMelhorCusto", "cMelhorCusto", "cMelhorCusto", ponto0, map0);
      trazAqui0.addUtilizador(utilizadores0);
      assertEquals("cMelhorCusto", utilizadores0.getNome());
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.iniciarEntregaV("r,.)Jt_W4EsU3Af@");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      trazAqui0.addEncomendaAceite(encomenda0);
      assertEquals(0.0F, encomenda0.getPeso(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      // Undeclared exception!
      try { 
        trazAqui0.encomendaFinalizada(encomenda0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      trazAqui0.addEncomenda(encomenda0);
      int int0 = trazAqui0.tempoMedioAtendimento("S~;WX4z&QjM,fi(qQ7?-");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      PlataformaEntrega plataformaEntrega0 = trazAqui0.getPlataformaEntrega("ToA7");
      assertNull(plataformaEntrega0);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      // Undeclared exception!
      try { 
        trazAqui0.distanciaUtilizador("c\"S6$\"Pzfs3", "c\"S6$\"Pzfs3");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("TrazAqui", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      EncomendasAceites encomendasAceites0 = trazAqui0.parseEncomendaAceite("0");
      assertEquals("0", encomendasAceites0.getCodEncomenda());
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      Encomenda encomenda0 = new Encomenda();
      trazAqui0.finalizarEncomenda(encomenda0);
      trazAqui0.gravaCSV("V{Z+v.*p%m");
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      TrazAqui trazAqui0 = new TrazAqui();
      TrazAqui trazAqui1 = new TrazAqui(trazAqui0);
      assertTrue(trazAqui1.equals((Object)trazAqui0));
      
      Encomenda encomenda0 = new Encomenda();
      trazAqui0.addEncomenda(encomenda0);
      boolean boolean0 = trazAqui1.equals(trazAqui0);
      assertFalse(boolean0);
  }
}
